image: docker:latest

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
- docker info

test:
  stage: test
  script:
  - docker build -t api-test -f api/Dockerfile ./api
  - docker run api-test npm test
  - docker build -t app-test -f app/Dockerfile ./app
  - docker run app-test npm test

deploy:
  stage: deploy
  script:
  - docker tag api-test registry.gitlab.com/mousetree/starter-pack/api-test
  - docker push registry.gitlab.com/mousetree/starter-pack/api-test
  - docker tag app-test registry.gitlab.com/mousetree/starter-pack/app-test
  - docker push registry.gitlab.com/mousetree/starter-pack/app-test