version: '3'
services:
  app:
    build: ./app
    command: npm start
    volumes:
      - ./app:/usr/app/src
      - /usr/app/src/node_modules
    ports:
      - 3000:3000
  api:
    build: ./api
    volumes:
      - ./api:/usr/app/src
      - /usr/app/src/node_modules
    ports:
      - 5000:5000
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://starterpack@postgres/starterpack
  postgres:
      image: postgres:10.2
      volumes:
        - ./data:/docker-entrypoint-initdb.d
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: starterpack
        POSTGRES_DB: starterpack