# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  checkout:
    steps:
      - checkout
  build_app:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
          - app-dependencies-{{ checksum "app/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - app-dependencies-
      - run: cd app && yarn install
      - save_cache:
          paths:
            - app/node_modules
          key: v1-dependencies-{{ checksum "app/package.json" }}
      - run: cd app && yarn test
  build_api:
      docker:
        - image: circleci/node:7.10
      working_directory: ~/repo
      steps:
        - restore_cache:
            keys:
            - api-dependencies-{{ checksum "api/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - api-dependencies-
        - run: cd api && yarn install
        - save_cache:
            paths:
              - api/node_modules
            key: api-dependencies-{{ checksum "app/package.json" }}
        - run: cd app && echo hello
workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout
      - build_app:
          requires:
            - checkout
      - build_api:
          requires:
            - checkout
